# Generated by Django 5.0.1 on 2024-02-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fuente', models.CharField(choices=[('Electronico', 'Electronico'), ('Impreso', 'Impreso')], default='Electronico', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Articulos',
            },
        ),
        migrations.CreateModel(
            name='AvanceProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reporte', models.CharField(max_length=50)),
                ('entregablesComprometidos', models.CharField(max_length=50)),
                ('entregablesReal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Avanceproyecto',
            },
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombrepublicacion', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Capitulos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaMinciencias',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C')], default='Junior', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Categoriaminciencias',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreEntidad', models.CharField(max_length=50)),
                ('paginaWeb', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Contenido',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Contrato',
            },
        ),
        migrations.CreateModel(
            name='CuartilEsperado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cuartil', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Q', 'Q'), ('RNT', 'RNT')], default='A', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Cuartilesperado',
            },
        ),
        migrations.CreateModel(
            name='EntidadPostulo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreInstitucion', models.CharField(max_length=50)),
                ('nombreGrupo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Entidadpostulo',
            },
        ),
        migrations.CreateModel(
            name='EntregableAdministrativo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('calidad', models.CharField(max_length=50)),
                ('entregable', models.CharField(max_length=50)),
                ('pendiente', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Entregableadministrativo',
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('resaccion', 'resaccion'), ('sometido', 'sometido'), ('publicado', 'publicado')], default='En proceso', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Estadoproducto',
            },
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Propuesta', 'Propuesta'), ('Iniciado', 'Iniciado'), ('Ejecucion', 'Ejecucion'), ('Finalizado', 'Finalizado'), ('Detenido', 'Detenido')], default='En proceso', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Estadoproyecto',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('fechaGrado', models.DateField()),
                ('codigoGrupo', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte')], default='CC', max_length=50)),
                ('numeroDocumento', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proyecto_Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechainicio', models.CharField(max_length=50)),
                ('fechafin', models.CharField(max_length=50)),
                ('numparticinerno', models.IntegerField()),
                ('numparticexterno', models.IntegerField()),
                ('tipoevento', models.CharField(choices=[('Congreso', 'Congreso'), ('Seminario', 'Seminario'), ('Simposio', 'Simposio'), ('Conferencia', 'Conferencia'), ('Encuentro academico', 'Encuentro academico'), ('Feria', 'Feria')], default='Congreso', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Eventos',
            },
        ),
        migrations.CreateModel(
            name='Financiacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valorPropuestoFin', models.CharField(max_length=50)),
                ('valorEjecutadoFin', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Financiacion',
            },
        ),
        migrations.CreateModel(
            name='Grupoinvestigacion',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Grupoinvestigacion',
            },
        ),
        migrations.CreateModel(
            name='GrupoInvestigacionPro',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Grupoinvestigacionpro',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'proyecto_Imagen',
            },
        ),
        migrations.CreateModel(
            name='Industrial',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('insitutofinanciador', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Industrial',
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('luegarpublicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Libros',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Licencia',
            },
        ),
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Lineainvestigacion',
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Maestria',
            },
        ),
        migrations.CreateModel(
            name='ModalidadProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modalidad', models.CharField(choices=[('general', 'general'), ('clinical', 'clinical'), ('creación', 'creación')], default='Convocatoria', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Modalidadproyecto',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('nacional', 'nacional'), ('internacional', 'internacional')], default='nacional', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Origen',
            },
        ),
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('NA', 'No aplica')], default='NA', max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Posgrado',
            },
        ),
        migrations.CreateModel(
            name='PregFinalizadoyCurso',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('reconocimientos', models.CharField(max_length=50)),
                ('numeroPaginas', models.IntegerField()),
            ],
            options={
                'db_table': 'proyecto_Pregfinalizadoycurso',
            },
        ),
        migrations.CreateModel(
            name='Pregrado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Pregrado',
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=50)),
                ('nombentidadotorgada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Reconocimientos',
            },
        ),
        migrations.CreateModel(
            name='RolProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Rolproducto',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tiporegistro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Software',
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('acta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Ubicacion',
            },
        ),
        migrations.CreateModel(
            name='UbicacionProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('instalacion', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Ubicacionproyecto',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto_Unidadacademica',
            },
        ),
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('año', models.DateField()),
                ('nombreEntidad', models.CharField(max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.contrato')),
            ],
            options={
                'db_table': 'proyecto_Consultoria',
            },
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('numerodocumento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipodocumento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte')], default='CC', max_length=2)),
                ('horasestricto', models.IntegerField()),
                ('horasformacion', models.IntegerField()),
                ('unidadAcademica', models.CharField(max_length=50)),
                ('categoriaminciencias', models.CharField(choices=[('Emérito', 'Eméritos'), ('Asociado', 'Asociados'), ('Senior', 'Senior'), ('Junior', 'Junior')], default='Junior', max_length=10)),
                ('escalofonodocente', models.CharField(max_length=50)),
                ('rolinvestigador', models.CharField(choices=[('Investigador', 'Investigador'), ('Administrador', 'Administrador'), ('Estudiante', 'Estudiante')], default='Investigador', max_length=50)),
                ('lineainvestigacion', models.CharField(max_length=50)),
                ('ies', models.CharField(max_length=50)),
                ('grupoinvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.grupoinvestigacion')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.imagen')),
                ('tipPosgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.posgrado')),
                ('tipPregrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.pregrado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ubicacion')),
            ],
            options={
                'db_table': 'proyecto_Investigador',
            },
        ),
        migrations.CreateModel(
            name='Coinvestigador',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coinvestigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador')),
            ],
            options={
                'db_table': 'proyecto_Coinvestigador',
            },
        ),
        migrations.CreateModel(
            name='Apropiacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('formato', models.CharField(max_length=50)),
                ('medio', models.CharField(max_length=50)),
                ('nombreEntidad', models.CharField(max_length=50)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.licencia')),
            ],
            options={
                'db_table': 'proyecto_Apropiacion',
            },
        ),
        migrations.CreateModel(
            name='ListaProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proyectoCursoProducto', models.CharField(blank=True, max_length=50, null=True)),
                ('proyectoFormuladoProducto', models.CharField(blank=True, max_length=50, null=True)),
                ('proyectoRSUProducto', models.CharField(blank=True, max_length=50, null=True)),
                ('apropiacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.apropiacion')),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.articulos')),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.capitulos')),
                ('consultoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.consultoria')),
                ('contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.contenido')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.eventos')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.libros')),
                ('prototipoIndustrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.industrial')),
                ('maestria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.maestria')),
                ('pregFinalizadoyCurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.pregfinalizadoycurso')),
                ('reconocimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.reconocimientos')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.software')),
            ],
            options={
                'db_table': 'proyecto_Listaproducto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tituloProducto', models.CharField(max_length=50)),
                ('tipologiaProducto', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('Productos tipo TOP', 'Productos tipo TOP')], default='En proceso', max_length=50)),
                ('publicacion', models.CharField(max_length=50)),
                ('estadoProdIniSemestre', models.CharField(max_length=50)),
                ('porcentanjeAvanFinSemestre', models.IntegerField()),
                ('observaciones', models.CharField(max_length=50)),
                ('porcentajeComSemestral', models.IntegerField()),
                ('porcentajeRealMensual', models.IntegerField()),
                ('fecha', models.DateField()),
                ('origen', models.CharField(max_length=5000)),
                ('Soporte', models.FileField(blank=True, max_length=1000, upload_to='uploadsProducto/')),
                ('categoriaMinciencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.categoriaminciencias')),
                ('cuartilEsperado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.cuartilesperado')),
                ('estadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproducto')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estudiantes')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador')),
                ('listaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.listaproducto')),
                ('rolProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.rolproducto')),
            ],
            options={
                'db_table': 'proyecto_Producto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=50)),
                ('investigadores', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('porcentajeEjecucionCorte', models.IntegerField()),
                ('porcentajeEjecucionFinCorte', models.IntegerField()),
                ('porcentajeAvance', models.IntegerField()),
                ('Soporte', models.FileField(blank=True, max_length=1000, upload_to='uploadsProducto/')),
                ('convocatoria', models.CharField(max_length=50)),
                ('nivelRiesgoEtico', models.CharField(max_length=50)),
                ('coinvestigadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.coinvestigador')),
                ('entidadPostulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidadpostulo')),
                ('entregableAdministrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entregableadministrativo')),
                ('estadoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproyecto')),
                ('financiacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.financiacion')),
                ('grupoInvestigacionPro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.grupoinvestigacionpro')),
                ('lineaInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.lineainvestigacion')),
                ('modalidadProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.modalidadproyecto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.origen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto')),
                ('transacciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.transacciones')),
                ('ubicacionProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ubicacionproyecto')),
                ('unidadAcademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.unidadacademica')),
            ],
            options={
                'db_table': 'proyecto_Proyecto',
            },
        ),
    ]
