# Generated by Django 2.2.3 on 2023-05-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupoinvestigacion',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='posgrado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pregrado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='investigador',
            fields=[
                ('numerodocumento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipodocumento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte')], default='CC', max_length=2)),
                ('tituloposgrado', models.CharField(max_length=50)),
                ('titulopregrado', models.CharField(max_length=50)),
                ('horasestricto', models.IntegerField()),
                ('horasformacion', models.IntegerField()),
                ('unidadAcademica', models.CharField(max_length=50)),
                ('categoriaminciencias', models.CharField(choices=[('Emérito', 'Eméritos'), ('Asociado', 'Asociados'), ('Senior', 'Senior'), ('Junior', 'Junior')], default='Junior', max_length=10)),
                ('escalofonodocente', models.CharField(max_length=50)),
                ('rolinvestigador', models.CharField(max_length=50)),
                ('lineainvestigacion', models.CharField(max_length=50)),
                ('ies', models.CharField(max_length=50)),
                ('grupoinvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.grupoinvestigacion')),
                ('tipPosgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.posgrado')),
                ('tipPregrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.pregrado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ubicacion')),
            ],
        ),
    ]
