# Generated by Django 5.0.1 on 2024-08-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=5000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='convocatoria',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estadoProceso',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupoInvestigacionPro',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='investigador',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='lineaInvestigacion',
            field=models.CharField(choices=[('Ingeniería de software y sociedad', 'Ingeniería de software y sociedad'), ('Ingeniería para la salud y el desarrollo biológico', 'Ingeniería para la salud y el desarrollo biológico'), ('Ingeniería y educación', 'Ingeniería y educación'), ('Ingeniería para la sostenibilidad de sistemas naturales', 'Ingeniería para la sostenibilidad de sistemas naturales')], default='Ingeniería de software y sociedad', max_length=1800),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad',
            field=models.CharField(choices=[('general', 'general'), ('clinical', 'clinical'), ('creación', 'creación')], default='general', max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nivelRiesgoEtico',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Sin riesgo', 'Sin riesgo')], default='Sin riesgo', max_length=500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='origen',
            field=models.CharField(choices=[('nacional', 'nacional'), ('internacional', 'internacional')], default='nacional', max_length=500),
        ),
    ]
