# Generated by Django 5.0.1 on 2024-07-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='correo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='lineainvestigacion',
            field=models.CharField(choices=[('Ingeniería de software y sociedad', 'Ingeniería de software y sociedad'), ('Ingeniería para la salud y el desarrollo biológico', 'Ingeniería para la salud y el desarrollo biológico'), ('Ingeniería y educación', 'Ingeniería y educación'), ('Ingeniería para la sostenibilidad de sistemas naturales', 'Ingeniería para la sostenibilidad de sistemas naturales')], default='Ingeniería de software y sociedad', max_length=180),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='unidadAcademica',
            field=models.CharField(choices=[('Facultad de Ingeniería', 'Facultad de Ingeniería'), ('Facultad de Ciencias', 'Facultad de Ciencias'), ('Facultad de Educación', 'Facultad de Educación')], default='Facultad de Ingeniería', max_length=180),
        ),
    ]
