# Generated by Django 5.0.1 on 2024-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplantrabajo',
            name='estado_fecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionplantrabajo',
            name='estado_manual',
            field=models.BooleanField(default=True),
        ),
    ]
