# Generated by Django 5.0 on 2024-03-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='coinvestigadores',
            field=models.ManyToManyField(to='proyecto.investigador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Coinvestigador',
        ),
    ]
