# Generated by Django 5.0.1 on 2024-07-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='producto',
            field=models.ManyToManyField(to='proyecto.producto'),
        ),
    ]
