# Generated by Django 5.0.1 on 2024-05-21 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='entidadPostulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidadpostulo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='financiacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.financiacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='transacciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.transacciones'),
        ),
    ]
