# Generated by Django 4.2.1 on 2023-06-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apropiacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('formato', models.CharField(max_length=50)),
                ('medio', models.CharField(max_length=50)),
                ('nombreEntidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fuente', models.CharField(choices=[('Electronico', 'Electronico'), ('Impreso', 'Impreso')], default='Electronico', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='avanceProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reporte', models.CharField(max_length=50)),
                ('entregablesComprometidos', models.CharField(max_length=50)),
                ('entregablesReal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='capitulos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombrepublicacion', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaMinciencias',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C')], default='Junior', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='consultoria',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('año', models.DateField()),
                ('nombreEntidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreEntidad', models.CharField(max_length=50)),
                ('paginaWeb', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cuartilEsperado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cuartil', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Q', 'Q'), ('RNT', 'RNT')], default='A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='entidadPostulo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreInstitucion', models.CharField(max_length=50)),
                ('nombreGrupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='entregableAdministrativo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('calidad', models.CharField(max_length=50)),
                ('entregable', models.CharField(max_length=50)),
                ('pendiente', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estadoProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('resaccion', 'resaccion'), ('sometido', 'sometido'), ('publicado', 'publicado')], default='En proceso', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estadoProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Propuesta', 'Propuesta'), ('Iniciado', 'Iniciado'), ('Ejecucion', 'Ejecucion'), ('Finalizado', 'Finalizado'), ('Detenido', 'Detenido')], default='En proceso', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('fechaGrado', models.DateField()),
                ('codigoGrupo', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte')], default='CC', max_length=50)),
                ('numeroDocumento', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechainicio', models.CharField(max_length=50)),
                ('fechafin', models.CharField(max_length=50)),
                ('numparticinerno', models.IntegerField()),
                ('numparticexterno', models.IntegerField()),
                ('tipoevento', models.CharField(choices=[('Congreso', 'Congreso'), ('Seminario', 'Seminario'), ('Simposio', 'Simposio'), ('Conferencia', 'Conferencia'), ('Encuentro academico', 'Encuentro academico'), ('Feria', 'Feria')], default='Congreso', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='financiacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valorPropuestoFin', models.CharField(max_length=50)),
                ('valorEjecutadoFin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupoInvestigacionPro',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='industrial',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('insitutofinanciador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('luegarpublicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='licencia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lineaInvestigacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='listaProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proyectoCursoProducto', models.CharField(max_length=50)),
                ('proyectoFormuladoProducto', models.CharField(max_length=50)),
                ('proyectoRSUProducto', models.CharField(max_length=50)),
                ('apropiacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.apropiacion')),
                ('articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.articulos')),
                ('capitulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.capitulos')),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.consultoria')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.contenido')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.eventos')),
                ('libros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.libros')),
            ],
        ),
        migrations.CreateModel(
            name='maestria',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modalidadProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modalidad', models.CharField(choices=[('general', 'general'), ('clinical', 'clinical'), ('creación', 'creación')], default='Convocatoria', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='origen',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('nacional', 'nacional'), ('internacional', 'internacional')], default='nacional', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pregFinalizadoyCurso',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('reconocimientos', models.CharField(max_length=50)),
                ('numeroPaginas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tituloProducto', models.CharField(max_length=50)),
                ('tipologiaProducto', models.CharField(max_length=50)),
                ('publicacion', models.CharField(max_length=50)),
                ('estadoProdIniSemestre', models.CharField(max_length=50)),
                ('porcentanjeAvanFinSemestre', models.IntegerField()),
                ('observaciones', models.CharField(max_length=50)),
                ('porcentajeComSemestral', models.IntegerField()),
                ('porcentajeRealMensual', models.IntegerField()),
                ('fecha', models.DateField()),
                ('origen', models.CharField(max_length=50)),
                ('Soporte', models.CharField(max_length=50)),
                ('categoriaMinciencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.categoriaminciencias')),
                ('cuartilEsperado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.cuartilesperado')),
                ('estadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproducto')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estudiantes')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador')),
                ('listaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.listaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='reconocimientos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=50)),
                ('nombentidadotorgada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rolProducto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tiporegistro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transacciones',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('acta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ubicacionProyecto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('instalacion', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unidadAcademica',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=50)),
                ('coinvestigador', models.CharField(max_length=50)),
                ('programaCoinvestigador', models.CharField(max_length=50)),
                ('entidadInstitucion', models.CharField(max_length=50)),
                ('areaDisciplinares', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('porcentajeEjecucionCorte', models.IntegerField()),
                ('porcentajeEjecucionFinCorte', models.IntegerField()),
                ('porcentajeAvance', models.IntegerField()),
                ('soporte', models.CharField(max_length=50)),
                ('convocatoria', models.CharField(max_length=50)),
                ('nivelRiesgoEtico', models.CharField(max_length=50)),
                ('entidadPostulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidadpostulo')),
                ('entregableAdministrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entregableadministrativo')),
                ('estadoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.estadoproyecto')),
                ('financiacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.financiacion')),
                ('grupoInvestigacionPro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.grupoinvestigacionpro')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador')),
                ('lineaInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.lineainvestigacion')),
                ('modalidadProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.modalidadproyecto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.origen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto')),
                ('transacciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.transacciones')),
                ('ubicacionProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ubicacionproyecto')),
                ('unidadAcademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.unidadacademica')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='rolProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.rolproducto'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='maestria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.maestria'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='pregFinalizadoyCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.pregfinalizadoycurso'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='prototipoIndustrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.industrial'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='reconocimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.reconocimientos'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.software'),
        ),
        migrations.AddField(
            model_name='consultoria',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.contrato'),
        ),
        migrations.AddField(
            model_name='apropiacion',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.licencia'),
        ),
    ]
