# Generated by Django 5.0.1 on 2024-08-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('horasestricto', models.IntegerField(default=0)),
                ('rol', models.CharField(max_length=150)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.investigador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
            options={
                'db_table': 'proyecto_PlanTrabajo',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPlanTrabajo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=150)),
                ('planTrabajo', models.ManyToManyField(to='proyecto.plantrabajo')),
            ],
            options={
                'db_table': 'proyecto_ConfiguracionPlanTrabajo',
            },
        ),
    ]
