# Generated by Django 4.2.1 on 2023-06-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_apropiacion_articulos_avanceproyecto_capitulos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaproducto',
            name='articulos',
        ),
        migrations.RemoveField(
            model_name='listaproducto',
            name='capitulos',
        ),
        migrations.RemoveField(
            model_name='listaproducto',
            name='eventos',
        ),
        migrations.RemoveField(
            model_name='listaproducto',
            name='libros',
        ),
        migrations.RemoveField(
            model_name='listaproducto',
            name='reconocimientos',
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.articulos'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='capitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.capitulos'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.eventos'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.libros'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='reconocimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.reconocimientos'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='apropiacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.apropiacion'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='consultoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.consultoria'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.contenido'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='maestria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.maestria'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='pregFinalizadoyCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.pregfinalizadoycurso'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='prototipoIndustrial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.industrial'),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.software'),
        ),
    ]
