# Generated by Django 5.0 on 2024-03-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_producto_categoriaminciencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fuente',
            field=models.CharField(choices=[('Electronico', 'Electronico'), ('Impreso', 'Impreso')], default='Electronico', max_length=50),
        ),
        migrations.AlterField(
            model_name='pregfinalizadoycurso',
            name='fechaInicio',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregfinalizadoycurso',
            name='numeroPaginas',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregfinalizadoycurso',
            name='reconocimientos',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
