# Generated by Django 5.0 on 2024-03-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_proyecto_coinvestigadores_alter_proyecto_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='coinvestigadores',
            field=models.ManyToManyField(related_name='proyectos', to='proyecto.investigador'),
        ),
    ]
