# Generated by Django 5.0.1 on 2024-09-06 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_proyecto_area_alter_proyecto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
