# Generated by Django 5.0.1 on 2024-05-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyecto_fecha_alter_proyecto_entidadpostulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
    ]
