# Generated by Django 5.0.1 on 2024-08-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_configuracionplantrabajo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplantrabajo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
