# Generated by Django 5.0.1 on 2024-08-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_plantrabajo_configuracionplantrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrabajo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.producto'),
        ),
    ]
