# Generated by Django 4.2.1 on 2023-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_listaproducto_articulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaproducto',
            name='proyectoCursoProducto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='proyectoFormuladoProducto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listaproducto',
            name='proyectoRSUProducto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
