# Generated by Django 5.0 on 2024-03-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_articulos_fuente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipologiaProducto',
        ),
    ]
