# Generated by Django 5.0 on 2024-04-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_producto_observacion_proyecto_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avanceentregableproducto',
            name='soporte',
            field=models.FileField(blank=True, max_length=1000, upload_to='uploadsAvancesProducto/'),
        ),
        migrations.AlterField(
            model_name='avanceentregableproyecto',
            name='soporte',
            field=models.FileField(blank=True, max_length=1000, upload_to='uploadsAvanceProyecto/'),
        ),
    ]
