# Generated by Django 5.0.1 on 2024-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
