# Generated by Django 5.0.1 on 2024-08-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_configuracionplantrabajo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplantrabajo',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plantrabajo',
            name='rol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
