# Generated by Django 5.0 on 2024-03-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_proyecto_coinvestigadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='coinvestigadores',
            field=models.ManyToManyField(to='proyecto.investigador'),
        ),
    ]
