# Generated by Django 5.0.1 on 2024-06-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_transacciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='acta',
            field=models.FileField(blank=True, max_length=1000, upload_to='uploadsProducto/'),
        ),
    ]
