# Generated by Django 5.0 on 2024-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_proyecto_coinvestigadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etapa',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Corregir', 'Corregir'), ('Espera', 'Espera')], default='Espera', max_length=50),
        ),
    ]
