# Generated by Django 5.0 on 2024-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_producto_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='coinvestigadores',
            field=models.ManyToManyField(to='proyecto.investigador'),
        ),
    ]
