# Generated by Django 5.0 on 2024-03-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_alter_proyecto_coinvestigadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='coinvestigadores',
        ),
    ]
