# Generated by Django 5.0 on 2024-03-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_remove_proyecto_coinvestigadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='coinvestigador',
            field=models.ManyToManyField(to='proyecto.investigador'),
        ),
    ]
