# Generated by Django 5.0 on 2024-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_proyecto_coinvestigador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(max_length=1500),
        ),
    ]
